### ISSUE TITLE
Image & Custom Image Panels Icon On Product Page

### ISSUE THREAD

**Issue by jabberdog** [jabberdog/SURYA-MAGE-1.9-001#1]
Hi Liam,

Amit wants to have displayed a message on Surya Image & Custom image panels a message that they are "Made In The UK" so George prepared an icon with this message (see the file attached which is png 200x200 exactly same size like the other icons in the middle area on product page).

What I need you to do is only in case of products that are filled under the 2 categories (Image & Custom Print Panels) instead of displaying the first icon from left to right with the "Delivery within 2-3 days" message (https://www.suryaheating.co.uk/media/catalog/product/fastdelivery.png) put the attached icon.

For the rest of the products within the store we keep the icon we now have with the "Delivery within 2-3 days" message.

Thanks,
Florin

**Comment by Florinnn** [comment]
Sorted with Ben.
