### ISSUE TITLE
Fix the blog style on Surya

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/SURYA-MAGE-1.9-001#19]
Hi Ben,

Take a look at the Wordpres blog Liam integrated with Fishpig and make it look more tidy in style. Have below a list with 10 points spotted there to give a clue what I mean when saying you need to style and make it look more tidy:
1. Into the grid listing with blot posts, style the extract from the text with the title to stay bit closer to the image.

2. Into the grid lististing with blog posts, make the block of a post listed clickable (put them under same a ahref, except the informative part saying: This entry was posted in [Category] on [date] by [Author].). That mean you can get rid of the READ ARTICLE button. 

3. The informative part saying "This entry was posted in [Category] on [date] by [Author]" you need to shorten it a bit to say just "Posted in [Category] on [date] by [Author]". Over the author name put the link to the corresponding author.

4. Style the Search bar into the sidebar area.

5. On the blog post, get rid of the big space which now exists in between the blog title and main menu.

6. From the blog post page -- **just from top area below the blog title**, you need to remove this bit saying "This entry was posted on [date] by [Author]. This ie because we have it at the end of the blog post too and doesn;t make sense to keep it duplicated.

7. Into the blog post page, at the end of the blog post there is a bit which sais "This entry was posted in [Category] on [date] by [Author]" you need to shorten it as suggested earlier to say just "Posted in [Category] on [date] by [Author]". Over the author name put the link to the author in question.

8.  Where it sais Next Post → you need to have instead of the Next Post the actual title of the blog post that the link points to. The same will go with the Previous Post →.

9. I think the blog title h1 if can remove the text-transform: uppercase and increase maybe its font-weight to make it look more bold.

10. Anything else you spot on there on style. (have in mind all devices incl. mobile & tablet).

Thanks,
Florin

**Comment by developerWLED** [comment]
Hi @Florinnn i managed to point 7. and so this is finialized

**Comment by Florinnn** [comment]
Point 7 looks good.

The only thing open is adding the "Read More" button which needs to be there since the whole block is not clickable.

**Comment by Florinnn** [comment]
Ben, just spotted 2 more issues so I will add them as #11 and #12:
11. Please remove the huge space above the author name into the author archive page (e.g https://www.suryaheating.co.uk/blog/author/mark/) which seems to be caused by the bradcrumbs.

12. As you can see into the above link (if take an author page like this: https://www.suryaheating.co.uk/blog/author/mark/) you will notice that WP doesn't allow the html simple tag to their job into the author bio description. Can you find a solution for it. Tried myself to add a function into functions.php to remove the filter WP applies to HTML tags, now just need the <p> tags to work there.

**Comment by developerWLED** [comment]
As discussed on skype, we have resolved other issues only 12 outstanding, which we need further assistance on.

**Comment by Florinnn** [comment]
Agree. Lets leave this ticket open until Saturday then and once sorted fully I'll close it.

**Comment by developerWLED** [comment]
Hi @Florinnn Point 12 has now been fixed, please see blog bio

**Comment by Florinnn** [comment]
Seems ok, will close it.
