### ISSUE TITLE
UK icon for products filled under Image & Custom Printed Categs

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/SURYA-MAGE-1.9-001#21]
Hi Ben,

As Amit said at some point we need to have (in the area with the 3 orangey images on top middle column of product page) an image to say Made In The UK **only** for the panel products filled under 2 categories: Image IR Panels (ID: 45), Custom IR Panels (ID: 62).

So this image: https://www.suryaheating.co.uk/media/catalog/product/fastdelivery.png needs to be replaced with the one attached to this ticket.

Needless to say that for the products were the new image is shown you need to change the title and alt attributes of the image from title="Delivery within 2-3 Days" alt="Delivery within 2-3 Days" **to** title="Made In The UK" alt="Made In The UK".

![MadeInTheUK.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/MadeInTheUK-40f0a679a33045a2ddba6782425615c7de6929a8da6e215b31c7adda0cf42fef.png)

**Comment by developerWLED** [comment]
Hi @Florinnn just to let you know i am beginning with this task.

**Comment by developerWLED** [comment]
HI florin, I have added this image ONLY on the custom and image category product view pages. please check screen shots attached.
![screen shot 2017-10-17 at 09 59 45](https://user-images.githubusercontent.com/29500145/31655948-460c55b2-b322-11e7-9780-3f2011951189.png)
![screen shot 2017-10-17 at 10 00 11](https://user-images.githubusercontent.com/29500145/31655949-4626a9a8-b322-11e7-8228-6e3e1a14d989.png)
![screen shot 2017-10-17 at 10 00 32](https://user-images.githubusercontent.com/29500145/31655950-4641ea42-b322-11e7-834d-fe0d60414b4c.png)

**Comment by developerWLED** [comment]
the screenshot of the WHITE iIR panels os just to show that there is no occurance of the uk image

**Comment by Florinnn** [comment]
That is good, then lets have the changes live.
