### ISSUE TITLE
Price overlaps the title on Related products area

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/SURYA-MAGE-1.9-001#23]
Hi Ben,

It seems after the last Sat changes done on Surya the price overlaps the product title into the related products area.
See below:
![Price overlaps title.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Price%20overlaps%20title-4259209dfccecafaceee1c73688483dea0e976d67c2a749d254d20e7c8643a9b.jpg)

**Comment by developerWLED** [comment]
Hi @Florinnn, please take a look at the attached screenshot before i upload.

**Comment by developerWLED** [comment]
![screen shot 2017-10-16 at 17 09 20](https://user-images.githubusercontent.com/29500145/31622632-dd238486-b294-11e7-825b-66c467046058.png)

**Comment by Florinnn** [comment]
Yes that looks decent.
