### ISSUE TITLE
Changes on the product listings in the grid list on category pages

### ISSUE THREAD

**Issue by Florinnn** [jabberdog/SURYA-MAGE-1.9-001#8]
Hi Ben,

As discussed we will need to work on several changes on the way the products are listed into the grid list on category pages on Surya as follows:
1. We need to have if possible a single a href block (clickable area for each of the products listed). As discussed there will be 2 cases:
a) Case when the product listed is simple product and will have into the grid list a button called Add to cart. In this case you need to ensure that the picture + title + price + reviews are into the same a href poiting to the product page WHILE the add to cart as button will continue to trigger the add to cart action as it does now.
b) Case when the product is configurable and so at the bottom of the listing of a specific product you will see a button called "View details". In this case you need to ensure we have a single clickable area which will include if technically possible all elements: picture, title, price + reviews, and the button with view details.

2. As discussed you need to implement as hoverable effect on desktop for the area with the listing of a product (which will be clickable) in such way when you hover the image of the product changes from the default one with a second one from the product gallery (it can be any image randomly from the gallery except from the default one of course). This is meant to increase a bit the experience of the user once browsing into the category pages by presenting a second image instance of the product whenever the user hovers over the products. So that to incentivise a bit to click further on and get them on the product page which is the place where we have a higher chance they can order.

3. Right next to the price row you need to bring in parallel the reviews count as discussed WHEN the product in question has at least 1 review present.

4. Would be good if can work on the overall look of the block. I mean specifically if can try to style a bit the title, price and reviews count font sizes and look to make it look a bit better (e.g tide up the spaces in between the "View details" blue button and the price row; try and test to make the title of the product a slightly bigger font size OR just a bigger font weight; ensure the rewiews count stay nicely in parallel with the price, if not possible because of space try and find a good placement for it).

5. If can style a bit to make the filtering criteria more "sexy" as we discussed on conf call would be perfect as now it looks pretty plain and that does not incentivise the customers make use of it more.

Thanks,
Florin

**Comment by developerWLED** [comment]
Hi @Florinnn  Case 1, 2 have been complete, i have not yet pushed, this is just an update.

**Comment by developerWLED** [comment]
Note: case 3 complete

**Comment by Florinnn** [comment]
I think you missed making the update live as I cant see that much changed live so far. So can't check it. I seen just the a hrefs being removed which is good and only 1 kept but nothing more than that. Can you double check if live is exactly what you want me to check?

Thanks,
Florin

**Comment by developerWLED** [comment]
Hi @Florinnn i have made these changes live now.

**Comment by Florinnn** [comment]
Hi Ben,

I have some comments:
1. Case 1 regarding the a hrefs was not sorted completely as far as I see. Go to a category page and inspect the view details button in the grid listing to see if you still kept a separate a href for it or not. The thing is that the scope of case 1 was exactly this one to clean up as much as possible. So in the 2 cases you have as explained initially in my ticket above: a) When into the grid list you have View details button you need to have all elements in the grid list meaning (image, title, price, reviews count and View details button) into the same a href. b) When into the grid list you have an Add to Cart button you need to have the following details (image, title, price, rewiews count) into a single a href then the Add to Cart outside of that as is now so that it will continue to trigger add to cart action if and when pressed.
2. Regarding the change on the colour of the price View details from blue to orange I think this is not a good idea as looks quite ugly to be honest. Every page now is full of orange and so none of the key parts on the page do not stand out. Very important point I wanted to make here is that I have seen that because of your colour change from blue to orange which I assume you did for the category page, even on the product page the title (which was black and needs to stay like that) and the price (which was blue and needs to have definitely a colour diffrent than that soft orange) are now orange too. Are you aware of that? Can you please when making such changes in CSS verify that pages you don't want do not get impacted by your style changes. So for this you need to come back unfortunately and bring the old style on this, then work out to specify colours apropriately. But as said test out as the idea with orange looks not that good I think. Reviews count right next to the price on the grid listing definitely needs a different colour than orange as it needs to have something different (maybe green or blue as it was before but not orange) and will also need a smaller font size as the reviews stars plus the reviews count below that both have a bigger height than the price whicg sits in parallel and the visual effect it creates is bad. Same goes to sidebar filter where now everything is orange and that orange is very soft and so is VERY hard to read.
3. Case 5 unfortuntely I don't think you sorted as we discussed. Single change I see (which looks not that good for the page) is again the change colour of the text from black to orange this time and also a bigger font size for the filtering headings. When we spoke (take a look specifically at the sidebar area of the Image category) we said also for the first block with filter by category name if you can use a function to replace a specific part that repeat on the titles of each category on top area of the sidebar as look both spammy and less user oriented since we have all like this: [A x B size] [Infrared Heating Panels]. Second part you need to replace it with "". Pay attention that when I say to replace that part I say if you can do this into the script/code area that creates the sidebar filter so do not change the name of these subcategories in back end of magento as that will mean their title will also be changed and we need to keep the subcategory titles like they are now on the apropriate category page for each of the categories. Also for the case 5 I did not see any other improvements, it continues to look the old style so let me know what exactly did you improved there or maybe double check maybe the update with this part did not saved online ( just to give an example I see the old headings for the filtering criteria names and they are placed into H1, that h1 need to dissapear from there completely. I mean for instance if go on the Image category if you look at the filtering criteria names Shop by: Category, Price, Wattage, Panel Size, Room etc all are H1, remove H1 tag and style them to look better).
4. Regarding the way category page looks now, yesterday I told in my mail that ideally when making a change into a specific template and also changing some style rules, you will need to verify if after your changes the page keeps responsive on all devices and all elements into the page look okay, do not overlap or any of that. Now I noticed that on mobile in the grid list images of the products do overlap. Can you please check that. I looked at it on Iphone.

My general feeling is that you will need to invest a bit more time to arrange it, test and try different styles for the elements of a product listing as except the image change on hover which looks very good so well done, the others don't look that well. Also try and validate your html to ensure page will comply with the basic rules as much as possible.
Thanks,
Florin

**Comment by developerWLED** [comment]
Hi @Florinnn 

a few things i'd like to point out on my work.

case 1(a href wrapping).
I have wrapped the entire "view Details" block in one single href but it would seem that for each individual element the HTML is applying them singularly rather than the whole element. i'm unsure why this is, maybe standard coding.

comments 2 & 3  (colour changes etc) 
The colours before where standard Magento colours, and i do not think this is appropriate for an live online store, i agree the colours on screen look a bit too much, maybe we could come up with a tertiary and quinary colour (3rd & 4th) that would be more suited to the surya site, and then we could apply them globally on such things as text and price etc as i just don't think we should leave the magento colours are appropriate too use.

Comment 3 (trim category links)
I will work towards a solution for this, as i think its more complicated than i anticipated, i was looking into it the other day.

Comment 4 (4)
I will make sure everything responsive,  sometimes chrome developer tools reflect changes differently to mobile.

**Comment by developerWLED** [comment]
UPDATE: comment 3.
The trim has been done
In terms of styling there is not much that can really be done with the filters
I'm working towards styling the product grid page, i will carry on in the more.
NOTE: none of my changes are yet live.

**Comment by Florinnn** [comment]
Hi Ben, As discussed you need to work out to improve and sort out the category page by tackling the following points:
1. Validate your html code and ensure there are no issues with it -- this would also help you maybe to understand why the a href is still being placed separately for image, price, title etc. The a href issue is open and we agreed you will look into it to see if we can do something about it.
2. Analyze the page speed with the tools either from browsers or the gtmetrix and Google page speed insights I gave you. At the moment the category page looks like loading slow, slower than prior last changes.
3. The stars for the reviews + the reviews count has to be of smaller size so that maximum the height of the 2 will be the font height of the price in parallel. The reviews stands out too much in comparison with the price now and we need to avoid that.
4. On the listing as we discovered on products having reviews, the link placed over the reviews count points wrongly to the reviews page WHILE it should point to the product page.
5. Sort out the colour issue across the site: we can't live anymore with all texts being orange there, so either try and have the colours we had in the past (price in blue, links in blue etc), or test and try different colour combination.
6. Regarding the filtering in sidebar:
a) remove as said the h1 and keep the filtering criteria with such a font size to stand out (can be slighly smaller than the one we now see, remove the orange colour and keep black or so as previosly was black if remembered correctly).
b) sort out so that in the end the product cound (x) will sit on same row with the filtering range (now as we can see the product count sits on a separate row from the filtering option).
7. Since we noticed you've had to change the mobile view for the listing by having a single product per row instead of 2 like we had we agreed will be a good chance for us to re-style the mobile view of the grid listing on Surya. So take as a reference the mobile view we have now on Wholesale and implement it as mobile view on Surya as well. That one assumes having one product per row as follows:
a) the product title;
b) below the product title you will have the product image on left and the elements from point c to e in parallel with the image;
c) first info in parallel with the image will be the price & reviews count & stars like you see on Wholesale.
d) below the price & reviews count you will list 3 tech specs which you will have to take from the product attributes (tech table) for each panel in this order:
- Dimensions (mm)
- Wattage
- Surface Temperature.

NOTE: on products except infrared panels (e.g Thermostats & Accessories) which have different attributes that Infrared panels do, you can display 2 tech attributes instead of 3 as they don't have that many attributes set up. The 2 attributes can be:
- Manufacturer;
- Warranty.
e) Below the tech attributes from point d) you will have either the View Details OR Add to Cart Button.

NOTE: have in mind the listing of a product has to be included into a bod border with a similar shade like is the case in the example from Wholesale and the fact that all information (EXCEPT the Add to Cart button) should be clickable on mobile and it should point to the product page as we want it to behave.
If have questions regarding this mobile view let me know and we can take a look together at one example on Wholesale to see what I mean.

8. On desktop view I think for the grid list would be a good idea if you can put the details of each product in the grid list into a border box with a thin shadow effect like we now have on Wholesale (so all elements presenting a product in the grid list will be placed inside a thin border box like we have on Wholesale for instance).

If have any other points that you wrote down during our chat please add to this list so that we do not miss any points.

**Comment by developerWLED** [comment]
Hi Florin,

All Items, apart from 1 and 2 have been complete on my local,
As for items 1 and 2 i have ran speed tests and ran the code through a HTML validator, and these will need a lot of work,
I will start on these today.

**Comment by Florinnn** [comment]
Hi Ben,

Below are the comments just for the desktop version: (the issues we discussed on skype) which you need to fix. Most of them have to do with the style going a bit crazy into the page:
A. Home page:
1. Main header with menu to fix.
2. Slider banner to sit nicely with text column.

B. Category pages:
1. Align the content within the page as discussed.
2. Fix the filtering criteria to be aligned nicely to left (e.g see the Price on Image IR Panels category on sidebar).
3. Fix count of products + Show all on the bar following the big banner on category pages.
4. Instead of Dimensions as attribute put "Size (mm)".
5.  Put the 3 tech attributes in a href as well so that to be clickable.
6. Get rid of the url fragment in case of products having at least 1 reviews which on gtrid listing will the reviews count displayed.
7. Make the title slightly bigger in font size for the product names into grid listing (try 16px instead of 14px).
8. Try and make the reviews count + the stars slightly smaller so that not to stand out that much in comparison with the price.
9. Fix the issue in the grid list with the rows getting broken.

C. Product page:
1. Align all elements into the page as they were prior to the latest changes.
2. Remove a bit from the space from Drop dop with the config option and the row with the add to cart button.

Wait for the feedback for mobile view from me.

**Comment by Florinnn** [comment]
Mobile version:
Below you can find what I managed to spot until the moment you rolled back because of the add to cart issue (so accordingly you have to fix the style for mobile view):
A. Category Page (see images below):
1. The image in the block presenting a product overlaps with the other details listed there.
2. You need to style the page numebering navigational area (at the top and at the bottom of the category grid listing) as looks bad now (this is also an issue for desktop by the way).
3. As a general feedback I assume the mobile view has also been affected by the latest changes you did and by the bootstrap update you did as the main content within the page has no left & right margins on mobile view as you can see (so for instance the left & right shadow borders from the block of each product listed is not visible).
4. On mobile view, in case of Image IR panel category I think would be good if you can hide the bit of heading saying "SHOP BY" which on mobile sits right below the discount code banner as is useless on mobile to stay there (the orangey FILTER bar I think tells it all for mobile users so this is why there is no need to have that heading saying "SHOP BY" on top of the page).
5. Same feedback like on desktop applies: put the attributes under the a href to be clickable on mobile too.
![CP_1.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CP_1-86f75b6e2f4851054b7d13757673933aded7ca12ffc8be96c3f7debcb827291b.jpg)
![CP_4.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CP_4-1d7b086a0f270850edb4ec86b13a848ccfe992bdbbf5aa09e5ef65e6f94dfc9c.jpg)
![CP_3.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CP_3-59911550969575b0656d4e4174b2f4f1d77bc937a331bdd66d11bed2a6f89315.jpg)
![CP_2.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CP_2-6ba6d5cb47ea299595b905786643d07ff82acf1bbb17a6ebb78e697bed3f9d28.jpg)
![CP_5.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/CP_5-3832e75269cac4440a9d2e8dc8ff33cd61ebdd1bf6aae1288e1a472c8610f5f1.jpg)

B. Product Page:
1. I think you need to align all elements into the page as on mobile the same issue occurs with the page elements not being nicely aligned one in relation to the other elements into the page. See images below.
2. Hide one of the 2 sidebar banners on mobile view that we now see as is non-sense for us to display 2 banners saying the same. They both are looking bad and occupy too much space so soon we can prepare a more square banner for mobiles to use there.

![PP_2.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/PP_2-45b4108b7b041a2d9ec03c05800c48788634b8d8767623ed3169ec5aaa039e0e.jpg)
![PP_3.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/PP_3-22aadf8a9305d118b1a9030db9109ff6e204f294d3030b9bb0e6197894927b8a.jpg)
![PP_1.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/PP_1-277d3f6ca68b533effb664b3ac851275d4076c5c9dbdb55db791df0d3af71cab.jpg)
![PP_5.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/PP_5-a4337a4616cd98ee9c1a8a0410daebb326d4b9ff4f0ada60c84f0e32ced21332.jpg)
![PP_4.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/PP_4-93a6eb55695a02d5896400e7b88246d4c2cff2d44ddf2c9395fdeb02b8bffcf8.jpg)

**Comment by Florinnn** [comment]
Part 2 of feedback on mobile view:
1. On the following categories the title of the first product in the grid list is NOT clickable on mobile so if you try and touch the area with the title in the hope it will point to the designated product page you will notice it doesn't work the link):
https://www.suryaheating.co.uk/glass-ir-heating-panels.html
https://www.suryaheating.co.uk/glass-ir-panels.html
https://www.suryaheating.co.uk/mirrored-ir-panels.html
https://www.suryaheating.co.uk/indoor-outdoor-bar-heaters.html
https://www.suryaheating.co.uk/thermostats.html

2. On search page (example https://www.suryaheating.co.uk/catalogsearch/result/?q=panel) both on mobile & desktop I see there are visible more than the 2/3 attributes in the grid list of the products listed for a specific search. If you look at that you will some of the attributes that are extra placed there have wrong values so definitely worths keeping just the 2/3 as we have it on category pages so clean up that part. See below:
![image.png](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/image-cb568ae8ad9d12f119aa3e64cf067251bf59ebb8a21caf88a90228e62ac682fa.png)

3. On product page the button with the pop up video I'd put it a bit more close to the edge of the browser so reduce a bit the bottom margin/padding for that button (maybe keep a half of that actual bottom padding you have now).

4. On product page, when you fix the page elements to be nicely aligned into the page for both mobile & desktop views, please ensure that on mobile the related products area looks nice: at the moment because of some right/left paddings in that area with the related products, the pictures of the related products look bad as they get squeezed into a space smaller than the scale of the images themselves.

5. The home page on mobile view seems like having some responsivity problem as the page gets a horizontal scroll bar at the bottom which shows some of the elements into the page does not fit & resize properly (I assume it has to do with the main menu on top).

6. On checkout page you will also need to fix the page so that all elements fit into the page nicely as now there is no right & left padding and so all fields get up to the edge of the browser looking quite bad (see below some printscreeens with what I mean):
![Checkout_1.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Checkout_1-b16a2abaae9bd93d46ce05ace6960aa2e1e116aab0a10a7d6b06352dbd85ceb3.jpg)
![Checkout_3.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Checkout_3-ce566d0215db91688bd462625b638a4e8dc9c7d75235455959994228fd67a8cd.jpg)
![Checkout_2.jpg](https://overvio-usercontent.s3.eu-central-1.amazonaws.com/Checkout_2-1954899182f4d340744d1f4508ec3eb5bdd3fc91a88022b69e07ef4aa49b2fc3.jpg)

I will update this ticket in case I spot on something else for now.

Thanks,
Florin

**Comment by developerWLED** [comment]
Hi Florin, All the cases are up on live now.

**Comment by Florinnn** [comment]
Hi Ben,

As discussed on skype the 10 points list with some stuff (most of them on style issues we spottted after latest changes). If any of the below points is unclear please let me know today as tomorrow & sat I will be off:
1. On White Panels category page ONLY, on desktop view -- aligning that bar on a single row only with the sort by, items count number, show a specific number of products as it should look like (on the other categories everything stais on a single row on that bar except this WHITE panels category -- as shown in my printscreens on skype.
2. Desktop view - On image category page,  on sidebar there is still a problem with the price filtering criteria as shown in my printscreens on skype (mozille & firefox -- this is the issue you said can;t replicate due to resolution).
3. On mobile view on category pages into the listing grid still the price is not clickable so needs sorting out (check if you need to add live your changes for that).
4. On mobile view on category pages into the listing grid you need to style a bit more the mobile view by: reducing the left margin for the title and the picture so that we in the end can have a slightly bigger square picture scalled to fit in the space that will result. Now the product picture is squeezed there and it seems we have space to make it a bit bigger. The same goes with the space in between the column with the picture and the column in parallel with the picture with the others details about the product which can be slightly reduced to get more space for the picture. Maybe try on mobile view to have the title/product name with a 1-2 size up in font size.
5. On mobile view on category pages would be good if you can reduce a bit the bottom margin/padding below the h1 title tag so that the banner will stay closer to the title.
6. On mobile view on product pages in the area with the Related products needs fixing the style: a) seems not aligned nicely with the rest of the content on the page b) images seem not scalled properly to fit in that area.
7. On mobile view on product pages, you need to align the title to left not centered as is now because it looks bad. The product gallery would be good if you can add a navigation arrows area into the gallery similar with what we now have on Wholesale for instance as the product little thumbnail images from galley are simply listed one after another and in case a product have more than 3 images it will pull down all content on the page (including the price & ordering block which is not good).
8. On mobile view on product pages at the bottom of the page you still kept both banners and as said you need to hide the 2 and maximum keep the banners we now have on sidebar in case they look better of course ( I mean as discussed keep just the 3 small banners we now have on sidebar with the warranty, home trial and delivery).
9. For the pop up if you can bring a bit up the video into the middle of the page more as on smaller mobile devices the 2 buttons seem too close to the bottom edge of the browser and seem hard to click on to see.
10. On mobile view on home page, we need to show up the products in the area with the featured area as now there is only the heading saying "FEATURED INFRARED HEATERS" with no products displayed below it.

Thanks,
Florin

**Comment by developerWLED** [comment]
HI @Florinnn, 
Did we address these points in the end, it was some time ago, i cannot remember if we did or not.

Thanks.

**Comment by Florinnn** [comment]
Hi,

Unfortunately some of the issues we did sort here were lost somehow then Liam did fix some of them I spotted last Saturday. However, what I think is still open here and should be fixed is:
**1.** There are still subcategory pages were the section with Sort By, Items Count & Page numbering is broken into 2 rows. I remember we did fix this, but seems now is not working fine on all subcategory pages. Have examples were this is broken:  
https://www.suryaheating.co.uk/custom-image-heating-panels/600-x-1000-printed-infrared-heating-panels.html
https://www.suryaheating.co.uk/custom-image-heating-panels/600-x-1200-printed-infrared-heating-panels.html
https://www.suryaheating.co.uk/custom-image-heating-panels/800-x-1200-printed-infrared-heating-panels.html
https://www.suryaheating.co.uk/custom-image-heating-panels/1000-x-1200-printed-infrared-heating-panel.html
https://www.suryaheating.co.uk/custom-image-heating-panels/600-x-600-printed-infrared-heating-panels.html
Same issue on search page: https://www.suryaheating.co.uk/catalogsearch/result/?q=panel

**2.** As mentioned in the ticket with the Ajax cart too, on Portrait Tablet View it seems that both on category pages BUT also on home page the product grid list is hidden by default so users cannot reach the products grid list. See the prinscreen below:
![portrait_tablet_view](https://user-images.githubusercontent.com/29812956/31169438-7f1ef490-a8f0-11e7-931e-26cc9742ecae.jpg)


**3.** On Mozilla Firefox into the sidebar area on pages where we have price filter, prices ranges are still not being aligned one after another (you can replicate this into pages like https://www.suryaheating.co.uk/custom-image-heating-panels.html AND this one https://www.suryaheating.co.uk/catalogsearch/result/?q=panel. **Mozilla Firefox version I tested with is: 55.0.3 (32-bit). Resolution: 1920 x 1080.** See printscreen:
![image_category and search sidebar](https://user-images.githubusercontent.com/29812956/31168971-200e8a98-a8ef-11e7-8076-647bd28f86b1.jpg)

Hope didn't miss anything.

Florin

**Comment by jabberdog** [comment]
Ok, just to comment on this.

It appears that the product list row was duplicated, one for desktop and one for mobile. This isn't the best way to do it. It makes the code very difficult to manage and even more difficult to read if you're not the one working on it.

So for now, I have removed the "mobile" view that was added and left the "desktop" view in. I have then adjusted the SASS to fix any immediate outstanding layout issues. 

You can fetch the latest code on master for SURYA-MAGE-1.9-001 to see those amendments.

**Comment by Florinnn** [comment]
Ben, just for the record: as we detailed on Skype with the shared screen there are few issues that need your attention and you have the list of all these. 
If have any questions, let me know.

**Comment by Florinnn** [comment]
All seems good so I will close it so that we can move on to next stuff.
